### ISSUE TITLE
Le lien vers le répo Git ne fonctionne pas sur le site officiel

### ISSUE THREAD

**Issue by PaulKempf** [LAB-MI/attestation-couvre-feu-covid-19#1]
https://media.interieur.gouv.fr/attestation-couvre-feu-covid-19/ -> Le lien en bas de page ne redirige pas ici.

**Comment by betalabmi** [comment]
oui. le code actuel de ce dépôt ne permet pas de générer le pdf.
nous préférons résoudre ce point avant de diffuser l'existence de ce dépôt en mettant le lien à jour.

**Comment by betalabmi** [comment]
la nouvelle version de l'attestation vient d'être mis en ligne. nous avons attendu la publication du décret et la mise à jour de la version pdf pour corriger en même temps le lien vers ce dépôt.

**Comment by PaulKempf** [comment]
C'est en effet corrigé ! Merci !
