### ISSUE TITLE
ajouter un motif "faire ces courses"

### ISSUE THREAD

**Issue by bmonti** [LAB-MI/attestation-couvre-feu-covid-19#11]

**Comment by bmillemathias** [comment]
pas avec cette faute alors

**Comment by raphpitt** [comment]
+1

**Comment by pierregoutagny** [comment]
Ce service sert à remplir automatiquement le [document fourni par le MI](https://github.com/LAB-MI/attestation-couvre-feu-covid-19/blob/master/src/certificate.pdf), pas de décider des motifs y existant. De plus, l'attestation de couvre-feu est obsolète dès ce soir... Il me semble que le nouveau dépôt où il (ne) faut (pas) poster ce genre d'issue est https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020
