### ISSUE TITLE
Ajouter le motif "aller à la plage"

### ISSUE THREAD

**Issue by SammyCOLIN** [LAB-MI/attestation-couvre-feu-covid-19#12]
Bonjour,

Serait-il possible d'ajouter le motif "aller à la plage" pour nous autres habitants du littoral.

Merci

**Comment by infosteph** [comment]
Bonjour,
Je vous invite sur ce point à faire remonter votre souhait au ministre de l'Intérieur via ce formulaire de contact :
https://www.interieur.gouv.fr/Contact/Ecrire-au-ministre-de-l-Interieur
Bien cordialement,

**Comment by Moranbzh** [comment]
Gérald a l'air occupé à régler ses problèmes judiciaires, il n'a pas encore pris le temps de me répondre. Vous en êtes où au niveau de la prochaine version de l'application pour le 3ème confinement ?

**Comment by SammyCOLIN** [comment]
Gérald à l'air occupé à régler ses problèmes judiciaires, il n'a pas encore pris le temps de me répondre. J'espère que ma demande sera prise en compte pour la prochaine version de l'application dédiée au 3ème confinement ! :)
