### ISSUE TITLE
Il manque la raison principale pour aller faire ses courses !

### ISSUE THREAD

**Issue by mikethetexan** [LAB-MI/attestation-couvre-feu-covid-19#14]
Erreur assez incroyable...

**Comment by Parad0xJ** [comment]
Absolument d'accord ! Ou est l'option : " faire ses courses " ?

**Comment by bigornoo** [comment]
Mais oui c'est fabuleux. Ça prouve que ceux qui font l'application ne l'utilisent pas. 
Fabuleux.

**Comment by gjgd** [comment]
Ce repo est pour l'attestation "couvre feu" pas l'attestation "confinement" qui commence ce soir.
Dans le cadre du couvre feu, il n'était pas permis de faire ses courses apres 21h (du moins il me semble, ça paraitrait logique vu que tout fermait à 21h)

**Comment by mikethetexan** [comment]
@gjgd , j'ai bien vu, mais c'est le seul lien que l'application tous anticovid envoie et même ce matin il n'y a pas de nouveau lien sur le site du ministère de l'Intérieur pour tout autre formulaire. la seule chose qu'ils ont fait pendant la nuit et de désactiver le formulaire du couvre-feu.
