### ISSUE TITLE
Autocompletion Chrome incomplète

### ISSUE THREAD

**Issue by kall2sollies** [LAB-MI/attestation-couvre-feu-covid-19#18]
L'autocompletion de Google chrome Android ne mémorise pas les champs suivants :

- date de naissance
- ville de naissance

**Comment by infosteph** [comment]
Bonjour, @kall2sollies 
Pouvez-vous nous dire si vous rencontrez toujours ce problème d'autocomplétion sur Google Chrome ?
Bien cordialement,

**Comment by kall2sollies** [comment]
Tout est corrigé !
