### ISSUE TITLE
Attestation pou déposer les enfants à l’école 

### ISSUE THREAD

**Issue by AndriVala** [LAB-MI/attestation-couvre-feu-covid-19#21]
Pourquoi on ne trouve pas de génération numérique d’attestation pour déposer les enfant à l’école...?

**Comment by infosteph** [comment]
Bonjour,
Le choix a été fait de ne pas développer de générateur pour les attestations spécifiques. Notre petite équipe se concentre sur le seul générateur d'attestation de déplacement dérogatoire en période de couvre-feu.
Bien cordialement,
