### ISSUE TITLE
Mention "durant les horaires de couvre-feu"

### ISSUE THREAD

**Issue by DatPenguin** [LAB-MI/attestation-couvre-feu-covid-19#25]
Bonjour,

Suite à la modification des horaires du couvre-feu à 18h dans certains départements, le générateur en ligne génère une attestation ayant pour en-tête "ATTESTATION DE DÉPLACEMENT DÉROGATOIRE DURANT LES HORAIRES DU COUVRE-FEU". Cette repo ne présente pas cette mise à jour, serait-il possible de faire concorder les deux svp ?

Merci et bonne année 2021

**Comment by betalabmi** [comment]
Bonjour,

Merci pour votre retour.
Le dépôt est à jour à présent.
